# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1035, 830)
        self.textEdit = QtWidgets.QTextEdit(Widget)
        self.textEdit.setGeometry(QtCore.QRect(220, 490, 611, 61))
        self.textEdit.setObjectName("textEdit")
        self.quit_button = QtWidgets.QPushButton(Widget)
        self.quit_button.setGeometry(QtCore.QRect(600, 580, 221, 61))
        self.quit_button.setObjectName("quit_button")
        self.send_button = QtWidgets.QPushButton(Widget)
        self.send_button.setGeometry(QtCore.QRect(220, 580, 221, 61))
        self.send_button.setObjectName("send_button")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(450, 80, 131, 51))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(Widget)
        self.listWidget.setGeometry(QtCore.QRect(220, 150, 611, 321))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Dialog"))
        self.quit_button.setText(_translate("Widget", "Quit"))
        self.send_button.setText(_translate("Widget", "Send"))
        self.label.setText(_translate("Widget", "PyQT Chat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QDialog()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
